// Code generated by "stringer -type=Cmd,Bank -output=const_string.go"; DO NOT EDIT.

package drive64

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CmdLoadFromPc-32]
	_ = x[CmdDumpToPc-48]
	_ = x[CmdVersionRequest-128]
}

const (
	_Cmd_name_0 = "CmdLoadFromPc"
	_Cmd_name_1 = "CmdDumpToPc"
	_Cmd_name_2 = "CmdVersionRequest"
)

func (i Cmd) String() string {
	switch {
	case i == 32:
		return _Cmd_name_0
	case i == 48:
		return _Cmd_name_1
	case i == 128:
		return _Cmd_name_2
	default:
		return "Cmd(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BankCARTROM-1]
	_ = x[BankSRAM256-2]
	_ = x[BankSRAM768-3]
	_ = x[BankFLASH-4]
	_ = x[BankPOKEMON-5]
	_ = x[BankEEPROM-6]
}

const _Bank_name = "BankCARTROMBankSRAM256BankSRAM768BankFLASHBankPOKEMONBankEEPROM"

var _Bank_index = [...]uint8{0, 11, 22, 33, 42, 53, 63}

func (i Bank) String() string {
	i -= 1
	if i >= Bank(len(_Bank_index)-1) {
		return "Bank(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Bank_name[_Bank_index[i]:_Bank_index[i+1]]
}
