name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Linux-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libftdi1-dev
      - name: Build libusb
        run: |
          mkdir /tmp/libusb
          cd /tmp/libusb
          wget -q https://github.com/libusb/libusb/releases/download/v1.0.24/libusb-1.0.24.tar.bz2
          tar xvf libusb-1.0.24.tar.bz2
          cd libusb-1.0.24
          ./configure --disable-dependency-tracking --disable-udev
          make
          sudo make install
      - name: Build Linux
        run: go build --tags 'netgo osusergo' -ldflags '-s -w -extldflags "-static"'
        env:
          PKG_CONFIG_PATH: /usr/local/lib/pkgconfig:/usr/lib/pkgconfig
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: g64drive-linux-amd64
          path: g64drive
