name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Build-Linux-Windows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libftdi1-dev mingw-w64
      # Build libusb from source. This is required to disable usage of udev
      # which in turns simplify static linking because Ubuntu doesn't ship with
      # a static version of udev (and that would require recompiling systemd).
      # udev supported is only useful for hotplugging, which we don't need anyway.
      - name: Build libusb
        run: |
          mkdir /tmp/libusb
          cd /tmp/libusb
          wget -q https://github.com/libusb/libusb/releases/download/v1.0.24/libusb-1.0.24.tar.bz2
          tar xvf libusb-1.0.24.tar.bz2
          cd libusb-1.0.24
          ./configure --disable-dependency-tracking --disable-udev
          make
          sudo make install
      - name: Build Linux
        run: go build --tags 'netgo osusergo' -ldflags '-s -w -extldflags "-static"'
        env:
          PKG_CONFIG_PATH: /usr/local/lib/pkgconfig:/usr/lib/pkgconfig
      - name: Upload Linux binary
        uses: actions/upload-artifact@v3
        with:
          name: g64drive-linux-amd64
          path: g64drive
      - name: Build Windows
        run: go build -ldflags '-s -w'
        env: 
          GOOS: windows
          GOARCH: amd64
          CGO_ENABLED: 1
          CC: "x86_64-w64-mingw32-gcc"
      - name: Upload Windows binary
        uses: actions/upload-artifact@v3
        with:
          name: g64drive-windows-amd64
          path: g64drive.exe

  Build-Mac:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - name: Install dependencies
        run: brew install libftdi libusb pkg-config
      # We want to do a build which doesn't depend on homebrew dynamic libraries
      # for libusb and libftdi1. To do so, we need to patch the cgo lines in libftdi1
      # to avoid using pkg-config and instead manually providing include paths and
      # library paths, including explcitly mentioning the .a files for the two libraries.
      - name: Patch for static build
        run: |
          go mod vendor
          export SED_SEARCH='#cgo darwin pkg-config.*'
          export SED_REPLACE1="#cgo darwin CFLAGS: -I$(brew --prefix)/include/libftdi1 -I$(brew --prefix)/include/libusb-1.0"
          export SED_REPLACE2="#cgo darwin LDFLAGS: $(brew --prefix)/lib/libftdi1.a $(brew --prefix)/lib/libusb-1.0.a -framework IOKit -framework CoreFoundation -framework Security"
          sed -i.bak "s|$SED_SEARCH|$SED_REPLACE1\\n$SED_REPLACE2|" vendor/github.com/ziutek/ftdi/device.go
      - name: Build
        run: go build -ldflags '-s -w'
      - name: Upload Linux binary
        uses: actions/upload-artifact@v3
        with:
          name: g64drive-mac-amd64
          path: g64drive
